// Code generated by hack/fixtures/gen-go.go from hack/fixtures/*.json. DO NOT EDIT.
// Regenerate with `.\build.ps1 fixtures-go` (or `.\build.ps1 fixtures` to also
// refresh hack/fixtures/*.json from live accounts first).
package fixtures

// CodexJSON is the compacted content of hack/fixtures/sample-codex.json.
var CodexJSON = []byte(`{"plan":"plus","fiveHour":33,"sevenDay":16,"fiveHourResetIn":18000,"sevenDayResetIn":508961,"fetchedAt":"2026-09-02T00:14:07+09:00"}`)

// ClaudeJSON is the compacted content of hack/fixtures/sample-claude.json.
var ClaudeJSON = []byte(`{"plan":"pro","buckets":[{"name":"5h","remaining":75,"resetTime":"2026-09-01T16:09:59.639605+00:00"},{"name":"7d","remaining":63,"resetTime":"2026-09-07T01:59:59.639631+00:00"}],"fetchedAt":"2026-09-02T00:14:08+09:00"}`)

// AntigravityJSON is the compacted content of hack/fixtures/sample-antigravity.json.
var AntigravityJSON = []byte(`{"groups":[{"name":"Gemini Models","buckets":[{"name":"Weekly Limit Remaining","window":"weekly","remaining":97,"resetTime":"2026-09-03T18:59:37Z"},{"name":"Five Hour Limit Remaining","window":"5h","remaining":100,"resetTime":"2026-09-01T20:14:17Z"}]},{"name":"Claude and GPT models","buckets":[{"name":"Weekly Limit Remaining","window":"weekly","remaining":100,"resetTime":"2026-09-08T15:14:17Z"},{"name":"Five Hour Limit Remaining","window":"5h","remaining":100,"resetTime":"2026-09-01T20:14:17Z"}]}],"fetchedAt":"2026-09-02T00:14:08+09:00"}`)
