package app

import (
	"testing"
	"time"

	"github.com/jmnote/aigauge/internal/providers"
)

func TestAppGetVersionAndThemeOverride(t *testing.T) {
	AppVersion = "v1.2.3"
	ThemeOverride = "dark"

	app := NewApp(nil, nil, nil, nil)
	if app.GetVersion() != "v1.2.3" {
		t.Errorf("GetVersion() = %q, want %q", app.GetVersion(), "v1.2.3")
	}
	if app.GetThemeOverride() != "dark" {
		t.Errorf("GetThemeOverride() = %q, want %q", app.GetThemeOverride(), "dark")
	}
}

func TestAppSetAlwaysOnTop(t *testing.T) {
	var onTopState bool
	app := NewApp(nil, nil, func(top bool) {
		onTopState = top
	}, nil)

	app.SetAlwaysOnTop(true)
	if !onTopState {
		t.Error("onSetAlwaysOnTop was not called with true on SetAlwaysOnTop")
	}

	app.SetAlwaysOnTop(false)
	if onTopState {
		t.Error("onSetAlwaysOnTop was not called with false on SetAlwaysOnTop")
	}
}

func TestAppSetContentHeight(t *testing.T) {
	var capturedHeight int
	onContentHeight := func(height int) {
		capturedHeight = height
	}

	app := NewApp(onContentHeight, nil, nil, nil)
	app.SetContentHeight(350)
	if capturedHeight != 350 {
		t.Errorf("Height captured = %d, want 350", capturedHeight)
	}

	app.SetContentHeight(10) // below min
	if capturedHeight != 80 {
		t.Errorf("Height clamped = %d, want 80", capturedHeight)
	}

	app.SetContentHeight(5000) // above max
	if capturedHeight != 1600 {
		t.Errorf("Height clamped = %d, want 1600", capturedHeight)
	}
}

func TestAppSetWindowWidth(t *testing.T) {
	var capturedWidth int
	app := NewApp(nil, func(width int) {
		capturedWidth = width
	}, nil, nil)

	app.SetWindowWidth(320)
	if capturedWidth != 320 {
		t.Errorf("Width captured = %d, want 320", capturedWidth)
	}

	app.SetWindowWidth(100)
	if capturedWidth != 200 {
		t.Errorf("Minimum width = %d, want 200", capturedWidth)
	}

	app.SetWindowWidth(900)
	if capturedWidth != 600 {
		t.Errorf("Maximum width = %d, want 600", capturedWidth)
	}
}

func TestAppHideToTray(t *testing.T) {
	called := false
	app := NewApp(nil, nil, nil, func() {
		called = true
	})

	app.HideToTray()
	if !called {
		t.Error("onHideToTray was not called by HideToTray")
	}
}

func TestAppSetGlobalHotkey(t *testing.T) {
	var enabled bool
	var shortcut string
	app := NewApp(nil, nil, nil, nil, func(gotEnabled bool, gotShortcut string) error {
		enabled = gotEnabled
		shortcut = gotShortcut
		return nil
	})

	if err := app.SetGlobalHotkey(true, "Super+Shift+`"); err != nil {
		t.Fatalf("SetGlobalHotkey() error = %v", err)
	}
	if !enabled || shortcut != "Super+Shift+`" {
		t.Errorf("SetGlobalHotkey() forwarded (%v, %q), want (true, %q)", enabled, shortcut, "Super+Shift+`")
	}
}

// TestSampleUsageShiftsFixtureTimestampsToNow exercises the sample-data preview
// against the real bundled fixtures (internal/app/fixtures, generated by
// hack/fixtures/gen-go.go from hack/fixtures/*.json) rather than synthetic
// data, so it also catches the fixtures themselves becoming malformed or
// unparseable.
func TestSampleUsageShiftsFixtureTimestampsToNow(t *testing.T) {
	app := NewApp(nil, nil, nil, nil)
	before := time.Now()

	codex := app.GetSampleCodexUsage()
	claude := app.GetSampleClaudeUsage()
	antigravity := app.GetSampleAntigravityUsage()

	after := time.Now()

	if codex.Error != "" {
		t.Fatalf("GetSampleCodexUsage() returned error: %s", codex.Error)
	}
	if codex.Plan != "plus" || codex.FiveHourIn != 18000 || codex.SevenDayIn != 508961 {
		t.Errorf("GetSampleCodexUsage() = %+v, want fixture values with plan/reset-in preserved", codex)
	}
	assertWithinWindow(t, "Codex FetchedAt", codex.FetchedAt, before, after)

	if claude.Error != "" {
		t.Fatalf("GetSampleClaudeUsage() returned error: %s", claude.Error)
	}
	assertWithinWindow(t, "Claude FetchedAt", claude.FetchedAt, before, after)
	if len(claude.Buckets) != 2 {
		t.Fatalf("GetSampleClaudeUsage() buckets = %d, want 2", len(claude.Buckets))
	}
	// The fixture's 5h bucket originally reset ~56 minutes after its
	// fetchedAt (resetTime 16:09:59 UTC vs. fetchedAt 15:14:08 UTC).
	// Shifted to "now" it should still be ~56 minutes after the new
	// FetchedAt, proving the original fetchedAt->resetTime interval was
	// preserved rather than the raw fixture timestamp being reused as-is.
	claudeFetched, _ := time.Parse(time.RFC3339, claude.FetchedAt)
	fiveHourReset, err := time.Parse(time.RFC3339, claude.Buckets[0].ResetTime)
	if err != nil {
		t.Fatalf("Claude bucket[0].ResetTime = %q is not parseable: %v", claude.Buckets[0].ResetTime, err)
	}
	gotDelta := fiveHourReset.Sub(claudeFetched)
	wantDelta := 55*time.Minute + 52*time.Second // resetTime(16:09:59.64Z) - fetchedAt(00:14:08+09:00 == 15:14:08Z)
	if diff := gotDelta - wantDelta; diff < -time.Minute || diff > time.Minute {
		t.Errorf("Claude bucket[0] reset-fetch delta = %v, want ~%v", gotDelta, wantDelta)
	}

	if antigravity.Error != "" {
		t.Fatalf("GetSampleAntigravityUsage() returned error: %s", antigravity.Error)
	}
	assertWithinWindow(t, "Antigravity FetchedAt", antigravity.FetchedAt, before, after)
	if len(antigravity.Groups) != 2 {
		t.Fatalf("GetSampleAntigravityUsage() groups = %d, want 2", len(antigravity.Groups))
	}
	for _, group := range antigravity.Groups {
		for _, bucket := range group.Buckets {
			if _, err := time.Parse(time.RFC3339, bucket.ResetTime); err != nil {
				t.Errorf("Antigravity bucket %q ResetTime = %q is not parseable: %v", bucket.Name, bucket.ResetTime, err)
			}
		}
	}
}

// TestSampleUsageReportsConnected keeps the preview rendering through the same
// connected-state path as a real provider, so the reviewer sees the actual
// gauges rather than an empty or error-shaped card.
func TestSampleUsageReportsConnected(t *testing.T) {
	app := NewApp(nil, nil, nil, nil)
	for name, status := range map[string]providers.Status{
		"codex":       app.GetSampleCodexUsage().Status,
		"claude":      app.GetSampleClaudeUsage().Status,
		"antigravity": app.GetSampleAntigravityUsage().Status,
	} {
		if status != providers.StatusConnected {
			t.Errorf("%s sample Status = %q, want %q", name, status, providers.StatusConnected)
		}
	}
}

func assertWithinWindow(t *testing.T, label, value string, before, after time.Time) {
	t.Helper()
	got, err := time.Parse(time.RFC3339, value)
	if err != nil {
		t.Fatalf("%s = %q is not parseable: %v", label, value, err)
	}
	if got.Before(before.Add(-time.Second)) || got.After(after.Add(time.Second)) {
		t.Errorf("%s = %v, want between %v and %v", label, got, before, after)
	}
}
