//go:build ignore

// Command gen-go reads the raw sample-*.json fixtures written by
// hack/fixtures/gen-json.go (hack/fixtures/*.json) and generates
// internal/app/fixtures/fixtures.go, embedding each fixture's JSON as a Go
// byte-slice constant. The app's sample-data preview (internal/app.App)
// imports that generated package directly, so the sample data compiles
// straight into the binary with no go:embed/fs.FS/file-read step involved -
// just json.Unmarshal against an in-memory []byte like any other constant.
//
// Run via `.\build.ps1 fixtures-go` from the repository root (or
// `.\build.ps1 fixtures` to also refresh hack/fixtures/*.json from live
// accounts first). internal/app/fixtures/fixtures.go is checked into git -
// like any generated code, `go build` does not regenerate it on its own, so
// re-run this after changing hack/fixtures/*.json and commit the result.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/jmnote/aigauge/internal/providers"
)

func main() {
	sourceDir := filepath.Join("hack", "fixtures")
	outPath := filepath.Join("internal", "app", "fixtures", "fixtures.go")

	codex := readAndValidate(sourceDir, "sample-codex.json", &providers.CodexUsage{})
	claude := readAndValidate(sourceDir, "sample-claude.json", &providers.ClaudeUsage{})
	antigravity := readAndValidate(sourceDir, "sample-antigravity.json", &providers.AntigravityUsage{})

	var body strings.Builder
	body.WriteString("// Code generated by hack/fixtures/gen-go.go from hack/fixtures/*.json. DO NOT EDIT.\n")
	body.WriteString("// Regenerate with `.\\build.ps1 fixtures-go` (or `.\\build.ps1 fixtures` to also\n")
	body.WriteString("// refresh hack/fixtures/*.json from live accounts first).\n")
	body.WriteString("package fixtures\n")
	writeConstant(&body, "Codex", "hack/fixtures/sample-codex.json", codex)
	writeConstant(&body, "Claude", "hack/fixtures/sample-claude.json", claude)
	writeConstant(&body, "Antigravity", "hack/fixtures/sample-antigravity.json", antigravity)

	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: format:", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: mkdir:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: write", outPath, err)
		os.Exit(1)
	}
	fmt.Println("Wrote", outPath)
}

// readAndValidate reads sourceDir/name and unmarshals it into out, so a
// fixture that no longer matches its provider's usage struct (a renamed
// field, a typo from hand-editing) fails loudly here at generate time
// instead of silently inside the sample preview at runtime.
func readAndValidate(sourceDir, name string, out any) []byte {
	path := filepath.Join(sourceDir, name)
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: read", path, err)
		os.Exit(1)
	}
	if err := json.Unmarshal(data, out); err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: parse", path, err)
		os.Exit(1)
	}
	return data
}

// writeConstant emits one fixture as a Go byte-slice constant, compacted.
// The checked-in hack/fixtures/*.json stays pretty-printed because a human
// reviews it before committing, but that indentation has no value once it is
// inside a single-line Go string literal - it only arrives as a wall of
// escaped newlines and spaces. Compacting is safe for every consumer: the
// fixtures are read back with json.Unmarshal, which does not care about
// whitespace.
func writeConstant(body *strings.Builder, varName, sourcePath string, data []byte) {
	var compact bytes.Buffer
	if err := json.Compact(&compact, data); err != nil {
		fmt.Fprintln(os.Stderr, "gen-go: compact", sourcePath, err)
		os.Exit(1)
	}
	fmt.Fprintf(body, "\n// %sJSON is the compacted content of %s.\n", varName, sourcePath)
	fmt.Fprintf(body, "var %sJSON = []byte(%s)\n", varName, goStringLiteral(compact.String()))
}

// goStringLiteral renders json as a Go string literal, preferring a raw one.
// JSON is mostly double quotes, so the interpreted form buries the data under
// backslashes (and sends any non-ASCII name through \u escapes) while the raw
// form reads as the JSON it is. A raw literal cannot contain a backtick, so
// data carrying one falls back to the escaped form. Escape sequences inside
// JSON strings survive either way: a raw literal leaves `\n` as the two
// characters JSON wants, and strconv.Quote doubles the backslash to the same
// effect.
func goStringLiteral(json string) string {
	if strings.Contains(json, "`") {
		return strconv.Quote(json)
	}
	return "`" + json + "`"
}
